// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9U0g-awzXNiyDeIoJDW0DP7VyZiilL8A',
    appId: '1:443979470762:web:cd305e155c21ea909cbdd3',
    messagingSenderId: '443979470762',
    projectId: 'push-notifications-fireb-b237f',
    authDomain: 'push-notifications-fireb-b237f.firebaseapp.com',
    storageBucket: 'push-notifications-fireb-b237f.appspot.com',
    measurementId: 'G-7N5B3KQ99K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZouL1Lcpc5yeWgTYpJzORpOXNPuZKK6I',
    appId: '1:443979470762:android:72b7cf1b7393efdf9cbdd3',
    messagingSenderId: '443979470762',
    projectId: 'push-notifications-fireb-b237f',
    storageBucket: 'push-notifications-fireb-b237f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4MbS9r9IAsrDHHCzNHMhLt7siGhrVGyE',
    appId: '1:443979470762:ios:7c822c991195aa329cbdd3',
    messagingSenderId: '443979470762',
    projectId: 'push-notifications-fireb-b237f',
    storageBucket: 'push-notifications-fireb-b237f.appspot.com',
    iosClientId: '443979470762-bo4abukvid8cdvtp1r9jgpc0snopj8u8.apps.googleusercontent.com',
    iosBundleId: 'br.com.marcellamaral.pushNotificationsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4MbS9r9IAsrDHHCzNHMhLt7siGhrVGyE',
    appId: '1:443979470762:ios:7c822c991195aa329cbdd3',
    messagingSenderId: '443979470762',
    projectId: 'push-notifications-fireb-b237f',
    storageBucket: 'push-notifications-fireb-b237f.appspot.com',
    iosClientId: '443979470762-bo4abukvid8cdvtp1r9jgpc0snopj8u8.apps.googleusercontent.com',
    iosBundleId: 'br.com.marcellamaral.pushNotificationsFirebase',
  );
}
